### ISSUE TITLE
language problem

### ISSUE THREAD

**Issue by shpj123** [thm-projects/frag.jetzt#7]
Hi there!
there seems to be some problem if my browser language is set other than german and the whole page got frozen.
![image](https://user-images.githubusercontent.com/50408937/141132649-1e9f8b9c-b080-4409-b258-363c4b65e656.png)
![image](https://user-images.githubusercontent.com/50408937/141132657-e4e50436-01d7-419d-9384-2e437ad6756f.png)

Best,
PJ

**Comment by kqc-real** [comment]
Thank you for pointing out the bug to us!

We have fixed it. Please test again.

**Comment by shpj123** [comment]
> Thank you for pointing out the bug to us!
> 
> We have fixed it. Please test again.

Hi there,
sadly it's still not working
![image](https://user-images.githubusercontent.com/50408937/143685306-b1a6cb87-710e-4e91-9e80-e7fec8c209ec.png)

Best PJ

**Comment by kqc-real** [comment]
We tested it with the DevTools, and it worked, see screenshot.

Did you reload the page?

<img width="1920" alt="Bildschirmfoto 2021-11-29 um 18 10 08" src="https://user-images.githubusercontent.com/5081170/143912421-2abf1ece-d2c6-4403-aeec-9a816003d84a.png">

**Comment by shpj123** [comment]
yes of course, since it's week ago...
However it's still not working.
Maybe you want to test it with the browser lang. settings instead of devtools?
edge://settings/languages

FYI: I'm on  96.0.1054.34, but it's a general bug everywhere I have zh as language in the settings 
![image](https://user-images.githubusercontent.com/50408937/143912753-ab071d56-2739-4a81-b298-e80499f2affd.png)

**Comment by kqc-real** [comment]
Please try again. This time it should work.

**Comment by shpj123** [comment]
> 

oh yes!
thx!
